[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = ['npm ci --production=false']

[phases.build]
cmds = ['npx prisma generate', 'npm run build:backend']

[start]
cmd = 'npm start'